### ISSUE TITLE
Error accedendo ao driver de jobs dende un proceso

### ISSUE THREAD

**Issue by alambike** [prefapp/catro-eixos-jobs#5]
Co driver de mongo, os procesos de **execTarea** non teñen acceso ao DRIVER_JOBS, polo que os procesos que o empleen cascan. 

Por exemplo Job.get_job:

```js
    __recogerInfoJob(){

        return this.tarea.sys["DRIVER_JOBS"].getJob(this.arg("id"))

    }
```
casca con:

```
   TypeError: Cannot read property 'getJob' of undefined
             at module.exports.__recogerInfoJob (/home/app/lib/procesos/api/job/job_get.js:24:45)
             at Promise (/home/app/node_modules/catro-eixos-js/lib/nucleo/ejecutor_paso.js:15:35)
             at Promise (<anonymous>)
             at module.exports.ejecutar (/home/app/node_modules/catro-eixos-js/lib/nucleo/ejecutor_paso.js:11:16)
             at module.exports.__r (/home/app/node_modules/catro-eixos-js/lib/nucleo/ejecutor.js:141:34)
             at /home/app/node_modules/catro-eixos-js/lib/nucleo/ejecutor.js:77:32
             at <anonymous> },
```

**Comment by frmadem** [comment]
Ahora se pasa del módulo de utiles y el acceso se hace siempre desde DRIVER_JOBS

```js

class MiProceso extends Proceso{

  __buscarJobs(){
 
    return this.sys("DRIVER_JOBS").buscarJobs({"meta.status": "PROCESSING"});
 }

}

```

Tiene un único problema este enfoque, se necesita derivar de ProcesoSwagger para poder acceder a los jobs.
